# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6edcc90c113e1a258651bb8a0cc953e132aa411b1b25709abed6e19de955dff7186591526fb9c325a498e967a5190fdfe17aeccef2088c0f4be49166ce57d2b2

test:
  secret_key_base: 6718b21690e1674c604696bfa80abcea493532e6decca886cf13ff8f5537441f92feb3979643e0a4c30157f8db6352bb4048ac1c0b0aeb443ba8b337479a2e36

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
